[project]
name = "agent-factory"
version = "0.1.0"
description = ""
authors = [
    {name = "MS",email = "mykola_shumskiy@outlook.pt"}
]
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
